name: Bug Report
description: Report a bug in yoetz
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `yoetz ask -p "test" --provider openai`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: yoetz version
      description: Output of `yoetz --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Provider
      description: Which LLM provider were you using?
      options:
        - OpenAI
        - Gemini
        - OpenRouter
        - LiteLLM
        - Browser (ChatGPT)
        - N/A
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information (error messages, logs, `--debug` output).
