name: Feature Request
description: Suggest an enhancement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: "I need to use provider X but it's not supported..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of yoetz does this affect?
      options:
        - Ask / Council
        - Review
        - Bundle
        - Generate (Image/Video)
        - Browser
        - Pricing / Budget
        - Configuration
        - CLI / UX
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant information.
